### ISSUE TITLE
Session Credentials

### ISSUE THREAD

**Issue by InSasquatchCountry** [isPique/Instaloader-Scripts#1]
I wasn't able to follow your prescribed method but had found this script from another repo and was able just copy and past all of what it scraped into /Users/user/.config/instaloader/session into your cookies.txt and it worked. I just opend firefox and logged in before running this script. You may want to include somehow.

https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py

**Comment by isPique** [comment]
Yea, I have seen that script before, but the method I use is mostly for users who use Chrome.
